{
 "title": "KIE",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Rejected by customer (count)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "fraud_rejected_amount_bucket", "legendFormat": "{{le}}" }
   ]
  },
  {
   "title": "Rejected by customer (rate)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(fraud_rejected_amount_bucket[5m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Approved by customer (count)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "fraud_approved_amount_bucket", "legendFormat": "{{le}}" }
   ]
  },
  {
   "title": "Approved by customer (rate)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(fraud_approved_amount_bucket[5m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Automatically approved (low amount)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "fraud_approved_low_amount_sum", "legendFormat": "fraud_approved_low_amount_sum" }
   ]
  },
  {
   "title": "Automatically approved (low amount)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(fraud_approved_low_amount_sum[5m])",
     "legendFormat": "fraud_approved_low_amount_sum rate"
    }
   ]
  },
  {
   "title": "Under investigation (count)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fraud_investigation_amount_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Under investigation (rate)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(fraud_investigation_amount_bucket[5m])",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}