{
 "title": "Router",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Outgoing notifications",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "notifications_outgoing_total" }
   ]
  },
  {
   "title": "Outgoing notifications (rate)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(notifications_outgoing_total[5m])"
    }
   ]
  },
  {
   "title": "Customer responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "notifications_incoming_total", "legendFormat": "{{response}}" }
   ]
  },
  {
   "title": "Customer responses (rate)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(notifications_incoming_total[5m])",
     "legendFormat": "{{response}}"
    }
   ]
  }
 ]
}